structure de la page
depanama89/patrickkudiatu pull request #1
Opened 2024-11-21 19:59 UTC by depanama89

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE requested changes
Revois

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +        <span class="header__nav-logo">PATRICK KUDIATU</span>
Un lien

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +        <ul class="header__nav-menu">
Menu tag plutôt que UL

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +        <button class="header__nav-btn">Download CV</button>
Mettre le bouton ensemble avec les liens

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +          <div class="main__hero__left__about">
1. Revoir la structure en 3 blocs
2. Patrick est un titre principal

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +          <div class="main__hero__right__social">
Une liste d'images

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +        <p class="main__projet-desc">
La description est ensemble avec la liste des compétences

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +        <div class="main__projet__btns">
C'est une lioste des cométences

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +        <div class="main__projet__items">
C'est une liste

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +          <strong>Lets Design Together</strong>
Revois les titres des sections

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +            Lorem ipsum dolor sit amet consectetur. Tristique amet sed massa
Le titre et le label sont ensemble

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +      <section class="footer__container">
T'as pas besoin de ça

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +        <div class="footer__container__botton">
Cette div n'est pas importante

2024-11-21 20:10 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +        <div class="footer__container__sociaux">
Une liste

2024-11-22 13:48 UTC, depanama89 commented on index.html
> +        <div class="footer__container__sociaux">
done

2024-11-22 13:48 UTC, depanama89 commented on index.html
> +        <div class="footer__container__botton">
done @Sacre-MBIKU-WAKANE

2024-11-23 12:25 UTC, Sacre-MBIKU-WAKANE approved these changes

2024-11-23 12:25 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +          <p class="main__aboutme__right-contenu">
Le titre et la description dans un même block

2024-11-23 12:25 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +          <strong class="email__work__title">Lets work Together</strong>
C'est un titre

2024-11-23 12:25 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +        <h1 class="main__projet-title">My Projects</h1>
un h2 aussi

2024-11-23 12:25 UTC, Sacre-MBIKU-WAKANE commented on index.html
> +            <strong class="email__work__info-title">Lets work Together</strong>
C'est un titre

2024-11-23 12:26 UTC, merged